services:
    old_db_connection:
        class: MigrationBundle\Services\Connection
        arguments:
            - %database_host%
            - %database_user%
            - %database_password%
            - %old_db_name%

    migrator.user:
        class: MigrationBundle\Services\UserMigrator
        arguments:
            - '@migrator.repository.user'
            - '@user_bundle.repository.user'
            - '@migrator.repository.classified'
            - '@user_bundle.factory.password'
            - '@phone.cleaner'

    migrator.classified:
        class: MigrationBundle\Services\ClassifiedMigrator
        arguments:
            - '@migrator.repository.user'
            - '@user_bundle.repository.user'
            - '@migrator.repository.classified'
            - '@repository_classified'
            - '@repository_type'
            - '@migrator.repository.cities_to_classifieds'
            - '@repository_city'
            - '@migrator.image.repository'

    migrator.search:
        class: MigrationBundle\Services\SearchMigrator
        arguments:
            - '@migrator.search.repository'
            - '@repository.search'

    migrator.repository.user:
        class: MigrationBundle\Repository\UserRepository
        arguments: ['@old_db_connection']

    migrator.repository.classified:
        class: MigrationBundle\Repository\ClassifiedRepository
        arguments: ['@old_db_connection']

    migrator.repository.cities_to_classifieds:
        class: MigrationBundle\Repository\CitiesToClassifiedsRepository
        arguments:
            - '@old_db_connection'

    truncator:
        class: MigrationBundle\Services\Truncator
        arguments: ['@doctrine.dbal.default_connection']

    phone.cleaner:
        class: MigrationBundle\Utils\PhoneCleaner

    cabinete.repository:
        class: MigrationBundle\Repository\CabineteRepository
        arguments:
            - '@old_db_connection'

    migrator.cabinete:
        class: MigrationBundle\Services\CabineteMigrator
        arguments:
            - '@cabinete.repository'
            - '@repository_city'
            - '@repository.medical_center'

    migrator.image.repository:
        class: MigrationBundle\Repository\ImageRepository
        arguments:
            - '@old_db_connection'

    migrator.search.repository:
        class: MigrationBundle\Repository\SearchRepository
        arguments:
            - '@old_db_connection'


