services:
    image_path_builder_openstack:
        class: App\ImageBundle\Service\ImagePathBuilderOpenCloud

    repository.image:
        class: App\ImageBundle\Entity\Repository\ImageRepository
        factory: ["@doctrine", getRepository]
        arguments:
          - App\ImageBundle\Entity\Image

    image_factory:
        class: App\ImageBundle\Service\ImageFactory
